# Abstract  

Hyperparameters are parameters that are specified prior to running machine learning algorithms that have a large effect on the predictive power of statistical models. Knowledge of the relative importance of a hyperparameter to an algorithm and its range of values is crucial to hyperparameter tuning and creating effective models. 

The hyperparameter database allows users to visualize and understand how to choose hyperparameters that maximize the predictive power of their models. The hyperparameter database is created by running millions of hyperparameter values, calculating the individual conditional expectation of every hyperparameter on the quality of a model. The data science part need to generating models using H2O to find best hyperparameters

# Data Source

The dataset is from the website https://www.kaggle.com/econdata/predciting-price-transaction#trainPrice.csv . 
Housing price always been a popular item that people wants to predict. Since it is critical for us to find out the factors that affecting transaction price.  The data we collected and stored concerns predicting  housing transaction price which contains values of  cities, floors, unit area households counts and parking capacity, rooms, heat fuel, heat type and front door structure.

# Conceptual Schema 

- For each dataset, it has only one data description and one data distribution, and has serval different model.
- For each data description, it has only one dataset.
- For each data distribution, it has only one dataset.
- For each model, it has only one dataset, and one metadata.
- For each metadata, it has only one dataset and has only one hyperparameter table.
- For each hyperparameter table, it has only one metadata and one variable importance table.
- For each variable importance table, it has only one hyperparameter table.

# Old ERD

![OERD](images/OERD.png)

# New ERD

![NERD](images/NERD.png)

# Physical Model

![PM](images/PM.png)

## Part II - Physical Model

### Create the database

```sql
create table Twitter_singers (
singer_id varchar(50) primary key,
singer_name varchar(50),
singer_url varchar(2000),
singer_description varchar(1000),
singer_followers_count varchar(50)
);

drop table Twitter_singers;
SHOW VARIABLES LIKE "secure_file_priv";

sHOW GLOBAL VARIABLES LIKE 'local_infile';
SET GLOBAL local_infile = 'ON';
SHOW GLOBAL VARIABLES LIKE 'local_infile';

LOAD DATA local INFILE '/Users/cyyo/Desktop/twitter_singers.csv'
INTO TABLE Twitter_singers
CHARACTER SET latin1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SELECT * FROM Twitter_singers;

create table Company_data (
Company_name varchar(50) primary key,
Date_of_establishment varchar(50),
Artists_number INTEGER,
Typical_singers varchar(100)
);

LOAD DATA local INFILE '/Users/cyyo/Desktop/company_data.csv'
INTO TABLE Company_data
CHARACTER SET latin1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;


SELECT * FROM Company_data;

create table Spotify_singer_Account (
Spotify_singer_name varchar(50),
Spotify_singer_ID varchar(50) primary key,
Spotify_singer_followers INTEGER,
singer_spotify_popularity integer,
Spotify_singer_total_albums INTEGER,
Spotify_singer_top_1_related_artist varchar(50),
Spotify_singer_top_2_related_artist varchar(50),
Spotify_singer_top_3_related_artist varchar(50)
);
drop table Spotify_singer_Account;
LOAD DATA local INFILE '/Users/cyyo/Desktop/spotify_artist.csv'
INTO TABLE Spotify_singer_Account
CHARACTER SET latin1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;


SELECT * FROM Spotify_singer_Account;


create table Spotify_album (
singer_name varchar(50) ,
singer_id varchar(50),
album_name varchar(50),
album_id varchar(50) primary key,
album_relase_date varchar(100),
total_tracks Integer
);
drop table Spotify_album;
LOAD DATA local INFILE '/Users/cyyo/Desktop/spotify_album.csv'
INTO TABLE Spotify_album
CHARACTER SET latin1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;


SELECT * FROM Spotify_album;

create table Spotify_songs (
singer_name varchar(50) ,
singer_id varchar(50),
song_name varchar(50),
song_id varchar(100) primary key,
duration_ms Integer,
song_popularity integer,
album_name varchar(50),
album_id varchar(50)

);
drop table Spotify_songs;
LOAD DATA local INFILE '/Users/cyyo/Desktop/spotify_song.csv'
INTO TABLE Spotify_songs
CHARACTER SET latin1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;


SELECT * FROM Spotify_songs;

create table twitter_post (
singer_name varchar(50),
most_popular_post_ID varchar(50) primary key,
post_content varchar(200),
post_time varchar(100),
post_retweet_count Integer
);
drop table twitter_post;
LOAD DATA local INFILE '/Users/cyyo/Desktop/twitter_post.csv'
INTO TABLE twitter_post
CHARACTER SET latin1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;


SELECT * FROM twitter_post;


create table 24hr_twitter_post (
singer_name varchar(50),
recnet_post_ID varchar(50) primary key,
recnet_post_content varchar(200),
recnet_post_time varchar(100),
recnet_post_retweet_count Integer
);
drop table 24hr_twitter_post;
LOAD DATA local INFILE '/Users/cyyo/Desktop/recent_24hr.csv'
INTO TABLE 24hr_twitter_post
CHARACTER SET latin1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;


SELECT * FROM 24hr_twitter_post;
```

# 10 Use Cases

## Use Case 1 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
SELECT s.singer_name,c.Company_name
FROM (Twitter_singers s inner JOIN Company_data c ON c.Typical_singers = s.singer_name)
ORDER BY s.singer_name DESC
LIMIT 10;
```

```
+---------------+---------------------+
| singer_name   | Company_name        |
|---------------|---------------------|
| Taylor Swift  | Big Machine Records |
| Rihanna       | Def Jam Recordings  |
| KATY PERRY    | CAPITOL RECORDS.    |
| Bruno Mars    | Atlantic Records    |
| Avril Lavigne | RCA Rcords          |
| Ariana Grande | Republic Records    |
+---------------+---------------------+
```


## Use Case 2 <br>
Description: Get the most popular post content for the Twitter singers

```sql
SELECT s.singer_name,p.most_popular_post_ID,p.post_content
FROM (Twitter_singers s left JOIN twitter_post p ON s.singer_name = p.singer_name)
ORDER BY p.most_popular_post_ID DESC
LIMIT 8;
```

```
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| singer_name   | most_popular_post_ID | post_content                                                                                                                                           |
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ariana Grande | 1102985085719068672  | love someone in your life as much as Jake Tapper loves the US war machine. Man is always there like one of those we… https://t.co/IGhzrnYeWo           |
| KATY PERRY    | 1102866539433254918  | hi I’m wide awake and I can never say that without singing the katy perry song....lol                                                                  |
| Avril Lavigne | 1102763914368970752  | "I saw a lot of friends disappear," @AvrilLavigne says of her battle with #Lyme disease. "Now I keep my group small… https://t.co/EfNotExPk3           |
| Taylor Swift  | 1102697124830085120  | Strength of both 2019 draft &amp; 2019 free agency is defensive line. Good FA group for DTs &amp; 3-4 DE types even with Gr… https://t.co/YIUij4oP9n   |
| Chris Brown   | 1102692675231330304  | I'm glad Lady Gaga didn't stay in her lane. Same for Chris Jericho,Justin Timberlake, Mark Wahlberg,The Rock,etc. A… https://t.co/zqCpkS6wd5           |
| Justin Bieber | 1102670872010207235  | Cardi B's new video delivers East L.A. tacos and Bruno Mars:

https://t.co/FpLKl5Kx7w https://t.co/2wv7NFwulz                                          |
| Rihanna       | 1102548147497287680  | Report: Rihanna To Sell Office Supplies &amp; Garden Ware https://t.co/oGrLduJRuX https://t.co/5OYO85JaKS                                              |
| Maroon 5      | 1102468355762532352  | When is Justin Bieber gonna release new music                                                                                                          |
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
```


## Use Case 3 <br>
Description: Get the Twitter singers' recent post content in 24 hours 

```sql
SELECT s.singer_name,o.recnet_post_ID,o.recnet_post_content
FROM (Twitter_singers s left JOIN 24hr_twitter_post o ON s.singer_name = o.singer_name)
ORDER BY o.recnet_post_ID DESC
LIMIT 10;
```

```
+---------------+----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| singer_name   | recnet_post_ID | recnet_post_content                                                                                                                                                      |
+---------------+----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Taylor Swift  | 9.70649E+17    | â¨â¨â¨â¨â¨â¨â¨â¨â¨â¨â¨â¨â¨ https://t.co/KHNRCaKfU0                                                                                                          |
| Ariana Grande | 1.10293E+18    | Ť @starbucks cloud #cloudmacchiato #starbucksambassador #trythesoyversion ą https://t.co/y2LRAx33Sq                                                                  |
| KATY PERRY    | 1.10243E+18    | One of my favorite #AmericanIdol moments: turning uncle @LionelRichie into FASHUN ź                                                                                 |
| Bruno Mars    | 1.1017E+18     | Whatâs the plot tho? https://t.co/eh6m7hHB6Z                                                                                                                           |
| Maroon 5      | 1.10022E+18    | RT @maroon5: Blown away by these submissions on @yarntexts! Check out our favorites from "Girls Like Youâ! https://t.co/IeEZT9vX0Z https://âŚ"                        |
| Avril Lavigne | 1.09793E+18    | ¤icon. Youâre truly missed. https://t.co/8roMHjW70o                                                                                                                  |
| Lady Gaga     | 1.09473E+18    | ­â¤ď¸a Grammy for Joanne is more than me &amp; my family could ever dream of. I sang that version in one take, &amp; poured mâŚ https://t.co/QeiWEjfjF0             |
| Chris Brown   | 1.08675E+18    | #Undecided has hit @ministryofsoundâs R&amp;B Mixtape playlist! Stream exclusively on @applemusic now! 
Playlist link:âŚ https://t.co/bIZ89gxkGs                      |
| Rihanna       | 1.08196E+18    | For the â¤ď¸ of X. Get ready for @savagexfenty's Valentine's Day styles - out Jan. 9th! https://t.co/oG4Xocxo9a                                                        |
| Justin Bieber | 1.05745E+18    | @torikelly I have listened to this album 10 times in a row. Incredible                                                                                                   |
+---------------+----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+                                                          
```


## Use Case 4 <br>
Description: Get all the albums name and id from the Spotify singers'

```sql
SELECT s.Spotify_singer_name,o.album_id,o.album_name 
FROM (Spotify_singer_Account s left JOIN Spotify_album o ON s.Spotify_singer_name = o.singer_name)
ORDER BY o.album_id DESC
LIMIT 10;
```

```
+---------------------+------------------------+--------------------------------+
| Spotify_singer_name | album_id               | album_name                     | 
|---------------------|------------------------|--------------------------------|
| Maroon 5            | 75iQSBSaztFIAun9qLLCnb | Girls Like You (feat. Cardi B) |  
| Justin Bieber       | 6Fr2rQkZ383FcMqFyT7yPr | Purpose (Deluxe)               |  
| Taylor Swift        | 6DEjYFkNZh67HP7R9PSZvv | reputation                     |  
| Katy Perry          | 5MQBzs5YlZlE28mD9yUItn | PRISM (Deluxe)                 |  
| Lady Gaga           | 4sLtOBOzn4s3GDUv3c5oJD | A Star Is Born Soundtrack      |  
| Bruno Mars          | 4PgleR09JVnm3zY1fW3XBA | 24K Magic                      |   
| Avril Lavigne       | 3zXjR3y2dUWklKmmp6lEhy | Let Go                         |   
| Rihanna             | 3Q149ZH46Z0f3oDR7vlDYV | ANTI                           |   
| Ariana Grande       | 2fYhqwDWXjbpjaIJPEfKFw | thank u,next                   |   
| Chris Brown         | 0JOT3Ff4gJ939hqdeEpsZv | Undecided                      |   
+---------------------+------------------------+--------------------------------+
```


## Use Case 5 <br>
Description: Get all the songs name and id from the Spotify singers' which Singer have the most followers 

```sql
SELECT s.Spotify_singer_name,o.song_id,o.song_name 
FROM (Spotify_singer_Account s inner JOIN Spotify_songs o ON s.Spotify_singer_name = o.singer_name)
ORDER BY o.song_id DESC
LIMIT 10;
```

```
+---------------------+------------------------+------------------------------------------+
| Spotify_singer_name | song_id                | song_name                                |
+---------------------+------------------------+------------------------------------------+
| Chris Brown         | 7uiBocndm12aKbsdnQ3Scx | Undecided                                |
| Taylor Swift        | 6NFyWDv5CjfwuzoCkw47Xf | Delicate                                 |
| Maroon 5            | 6FRLCMO5TUHTexlWo8ym1W | Girls Like You (feat. Cardi B)           |
| Avril Lavigne       | 5xEM5hIgJ1jjgcEBfpkt2F | Complicated                              |
| Katy Perry          | 5jrdCoLpJSvHHorevXBATy | Dark Horse                               |
| Justin Bieber       | 50kpGaPAhYJ3sGmk6vplg0 | Love Yourself                            |
| Ariana Grande       | 4kV4N9D1iKVxx1KLvtTpjS | break up with your girlfriend, i'm bored |
| Lady Gaga           | 2VxeLyX666F8uXCJ0dZF8B | Shallow                                  |
| Rihanna             | 2aksifNn5ph8igDOkPBA02 | Love On The Brain                        |
| Bruno Mars          | 0KKkJNfGyhkQ5aFogxQAPU | That's What I Like                       |
+---------------------+------------------------+------------------------------------------+
```


## Use Case 6 <br>
Description: Get all the songs name,id and popularity and from the typical singers of the companies  which Singer have the most followers 

```sql
SELECT o.song_popularity,o.song_id,o.song_name,c.Company_name,c.Typical_singers
FROM ( Company_data c inner JOIN Spotify_songs o ON o.singer_name = c.Typical_singers)
ORDER BY o.song_id DESC
LIMIT 10;
```

```
+-----------------+------------------------+------------------------------------------+---------------------+-----------------+
| song_popularity | song_id                | song_name                                | Company_name        | Typical_singers |
+-----------------+------------------------+------------------------------------------+---------------------+-----------------+
|              80 | 6NFyWDv5CjfwuzoCkw47Xf | Delicate                                 | Big Machine Records | Taylor Swift    |
|              76 | 5xEM5hIgJ1jjgcEBfpkt2F | Complicated                              | RCA Rcords          | Avril Lavigne   |
|              77 | 5jrdCoLpJSvHHorevXBATy | Dark Horse                               | CAPITOL RECORDS.    | katy Perry      |
|              99 | 4kV4N9D1iKVxx1KLvtTpjS | break up with your girlfriend, i'm bored | Republic Records    | Ariana Grande   |
|              73 | 2aksifNn5ph8igDOkPBA02 | Love On The Brain                        |  Def Jam Recordings | Rihanna         |
|              84 | 0KKkJNfGyhkQ5aFogxQAPU | That's What I Like                       | Atlantic Records    | Bruno Mars      |
+-----------------+------------------------+------------------------------------------+---------------------+-----------------+
```


## Use Case 7 <br>
Description: Get all the Spotify singers' total albums who are the typical singers the the all ompany data

```sql
SELECT s.Spotify_singer_name,s.Spotify_singer_total_albums,c.Company_name
FROM (Spotify_singer_Account s inner JOIN Company_data c ON c.Typical_singers = s.Spotify_singer_name)
ORDER BY s.Spotify_singer_name DESC
LIMIT 10;
```

```
+---------------------+-----------------------------+---------------------+
| Spotify_singer_name | Spotify_singer_total_albums | Company_name        |
+---------------------+-----------------------------+---------------------+
| Taylor Swift        |                          49 | Big Machine Records |
| Rihanna             |                          48 |  Def Jam Recordings |
| Katy Perry          |                          34 | CAPITOL RECORDS.    |
| Bruno Mars          |                           7 | Atlantic Records    |
| Avril Lavigne       |                           7 | RCA Rcords          |
| Ariana Grande       |                          24 | Republic Records    |
+---------------------+-----------------------------+---------------------+
```


## Use Case 8 <br>
Description: Get the most popular post content for the Twitter singers

```sql
SELECT s.singer_name,p.most_popular_post_ID,p.post_content
FROM (Twitter_singers s left JOIN twitter_post p ON s.singer_name = p.singer_name)
ORDER BY p.most_popular_post_ID DESC
LIMIT 8;
```

```
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| singer_name   | most_popular_post_ID | post_content                                                                                                                                           |
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ariana Grande | 1102985085719068672  | love someone in your life as much as Jake Tapper loves the US war machine. Man is always there like one of those we… https://t.co/IGhzrnYeWo           |
| KATY PERRY    | 1102866539433254918  | hi I’m wide awake and I can never say that without singing the katy perry song....lol                                                                  |
| Avril Lavigne | 1102763914368970752  | "I saw a lot of friends disappear," @AvrilLavigne says of her battle with #Lyme disease. "Now I keep my group small… https://t.co/EfNotExPk3           |
| Taylor Swift  | 1102697124830085120  | Strength of both 2019 draft &amp; 2019 free agency is defensive line. Good FA group for DTs &amp; 3-4 DE types even with Gr… https://t.co/YIUij4oP9n   |
| Chris Brown   | 1102692675231330304  | I'm glad Lady Gaga didn't stay in her lane. Same for Chris Jericho,Justin Timberlake, Mark Wahlberg,The Rock,etc. A… https://t.co/zqCpkS6wd5           |
| Justin Bieber | 1102670872010207235  | Cardi B's new video delivers East L.A. tacos and Bruno Mars:

https://t.co/FpLKl5Kx7w https://t.co/2wv7NFwulz                                          |
| Rihanna       | 1102548147497287680  | Report: Rihanna To Sell Office Supplies &amp; Garden Ware https://t.co/oGrLduJRuX https://t.co/5OYO85JaKS                                              |
| Maroon 5      | 1102468355762532352  | When is Justin Bieber gonna release new music                                                                                                          |
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
```


## Use Case 9 <br>
Description: Get the most popular post content for the Twitter singers

```sql
SELECT s.singer_name,p.most_popular_post_ID,p.post_content
FROM (Twitter_singers s left JOIN twitter_post p ON s.singer_name = p.singer_name)
ORDER BY p.most_popular_post_ID DESC
LIMIT 8;
```

```
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| singer_name   | most_popular_post_ID | post_content                                                                                                                                           |
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ariana Grande | 1102985085719068672  | love someone in your life as much as Jake Tapper loves the US war machine. Man is always there like one of those we… https://t.co/IGhzrnYeWo           |
| KATY PERRY    | 1102866539433254918  | hi I’m wide awake and I can never say that without singing the katy perry song....lol                                                                  |
| Avril Lavigne | 1102763914368970752  | "I saw a lot of friends disappear," @AvrilLavigne says of her battle with #Lyme disease. "Now I keep my group small… https://t.co/EfNotExPk3           |
| Taylor Swift  | 1102697124830085120  | Strength of both 2019 draft &amp; 2019 free agency is defensive line. Good FA group for DTs &amp; 3-4 DE types even with Gr… https://t.co/YIUij4oP9n   |
| Chris Brown   | 1102692675231330304  | I'm glad Lady Gaga didn't stay in her lane. Same for Chris Jericho,Justin Timberlake, Mark Wahlberg,The Rock,etc. A… https://t.co/zqCpkS6wd5           |
| Justin Bieber | 1102670872010207235  | Cardi B's new video delivers East L.A. tacos and Bruno Mars:

https://t.co/FpLKl5Kx7w https://t.co/2wv7NFwulz                                          |
| Rihanna       | 1102548147497287680  | Report: Rihanna To Sell Office Supplies &amp; Garden Ware https://t.co/oGrLduJRuX https://t.co/5OYO85JaKS                                              |
| Maroon 5      | 1102468355762532352  | When is Justin Bieber gonna release new music                                                                                                          |
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
```


## Use Case 10 <br>
Description: Get the most popular post content for the Twitter singers

```sql
SELECT s.singer_name,p.most_popular_post_ID,p.post_content
FROM (Twitter_singers s left JOIN twitter_post p ON s.singer_name = p.singer_name)
ORDER BY p.most_popular_post_ID DESC
LIMIT 8;
```

```
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| singer_name   | most_popular_post_ID | post_content                                                                                                                                           |
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Ariana Grande | 1102985085719068672  | love someone in your life as much as Jake Tapper loves the US war machine. Man is always there like one of those we… https://t.co/IGhzrnYeWo           |
| KATY PERRY    | 1102866539433254918  | hi I’m wide awake and I can never say that without singing the katy perry song....lol                                                                  |
| Avril Lavigne | 1102763914368970752  | "I saw a lot of friends disappear," @AvrilLavigne says of her battle with #Lyme disease. "Now I keep my group small… https://t.co/EfNotExPk3           |
| Taylor Swift  | 1102697124830085120  | Strength of both 2019 draft &amp; 2019 free agency is defensive line. Good FA group for DTs &amp; 3-4 DE types even with Gr… https://t.co/YIUij4oP9n   |
| Chris Brown   | 1102692675231330304  | I'm glad Lady Gaga didn't stay in her lane. Same for Chris Jericho,Justin Timberlake, Mark Wahlberg,The Rock,etc. A… https://t.co/zqCpkS6wd5           |
| Justin Bieber | 1102670872010207235  | Cardi B's new video delivers East L.A. tacos and Bruno Mars:

https://t.co/FpLKl5Kx7w https://t.co/2wv7NFwulz                                          |
| Rihanna       | 1102548147497287680  | Report: Rihanna To Sell Office Supplies &amp; Garden Ware https://t.co/oGrLduJRuX https://t.co/5OYO85JaKS                                              |
| Maroon 5      | 1102468355762532352  | When is Justin Bieber gonna release new music                                                                                                          |
+---------------+----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
```

# 4 Views

## View 1 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
CREATE VIEW case_1 AS 
SELECT s.singer_name,c.Company_name
FROM (Twitter_singer s inner JOIN Company_data c ON c.Typical_singers = s.singer_name)
ORDER BY s.singer_name DESC
LIMIT 10;
```


## View 2 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
CREATE VIEW case_1 AS 
SELECT s.singer_name,c.Company_name
FROM (Twitter_singer s inner JOIN Company_data c ON c.Typical_singers = s.singer_name)
ORDER BY s.singer_name DESC
LIMIT 10;
```


## View 3 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
CREATE VIEW case_1 AS 
SELECT s.singer_name,c.Company_name
FROM (Twitter_singer s inner JOIN Company_data c ON c.Typical_singers = s.singer_name)
ORDER BY s.singer_name DESC
LIMIT 10;
```


## View 4 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
CREATE VIEW case_1 AS 
SELECT s.singer_name,c.Company_name
FROM (Twitter_singer s inner JOIN Company_data c ON c.Typical_singers = s.singer_name)
ORDER BY s.singer_name DESC
LIMIT 10;
```

# 10 Procedures

## Procedure 1 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```          


## Procedure 2 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```


## Procedure 3 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```


## Procedure 4 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```


## Procedure 5 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```


## Procedure 6 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```


## Procedure 7 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```


## Procedure 8 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```


## Procedure 9 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```


## Procedure 10 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
-- 1.
CREATE DEFINER=`root`@`localhost` PROCEDURE `album_amount`(albums_amount varchar(10))
BEGIN

SELECT s.Spotify_singer_name, s.Spotify_singer_total_albums, t.singer_followers_count
FROM Spotify_singer_Account s  INNER JOIN Twitter_singer t 
ON s.Spotify_singer_name = t.singer_name
WHERE s.Spotify_singer_total_albums > albums_amount;

END
```

# 4 Functions

## Function 1 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql


DELIMITER $$ 

CREATE DEFINER=`root`@`localhost` FUNCTION `GetSongPopularty`(songId VARCHAR(500)) RETURNS varchar(50) CHARSET utf8mb4
    DETERMINISTIC
BEGIN

  DECLARE song VARCHAR(50);

  SELECT song_popularity INTO song FROM Spotify_song 
  WHERE song_id = songId;

  RETURN song;

END $$
DELIMITER ;

- eg: '0PJIbOdMs3bd5AT8liULMQ'
```


## Function 2 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql
DELIMITER $$ 

CREATE DEFINER=`root`@`localhost` FUNCTION `GetSongPopularty`(songId VARCHAR(500)) RETURNS varchar(50) CHARSET utf8mb4
    DETERMINISTIC
BEGIN

  DECLARE song VARCHAR(50);

  SELECT song_popularity INTO song FROM Spotify_song 
  WHERE song_id = songId;

  RETURN song;

END $$
DELIMITER ;

- eg: '0PJIbOdMs3bd5AT8liULMQ'
```


## Function 3 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql


DELIMITER $$ 

CREATE DEFINER=`root`@`localhost` FUNCTION `GetSongPopularty`(songId VARCHAR(500)) RETURNS varchar(50) CHARSET utf8mb4
    DETERMINISTIC
BEGIN

  DECLARE song VARCHAR(50);

  SELECT song_popularity INTO song FROM Spotify_song 
  WHERE song_id = songId;

  RETURN song;

END $$
DELIMITER ;

- eg: '0PJIbOdMs3bd5AT8liULMQ'
```


## Function 4 <br>
Description: Get all the Twitter singers' name who are the typical singers the the all ompany data.

```sql


DELIMITER $$ 

CREATE DEFINER=`root`@`localhost` FUNCTION `GetSongPopularty`(songId VARCHAR(500)) RETURNS varchar(50) CHARSET utf8mb4
    DETERMINISTIC
BEGIN

  DECLARE song VARCHAR(50);

  SELECT song_popularity INTO song FROM Spotify_song 
  WHERE song_id = songId;

  RETURN song;

END $$
DELIMITER ;

- eg: '0PJIbOdMs3bd5AT8liULMQ'
```

# 10 Indexs

## Index 1 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 2 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 3<br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 4 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 5 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 6 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 7 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 8 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 9 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png) 


## Index 10 <br>

```sql
select song_popularity from Spotify_song;
CREATE INDEX get_song_popularity
ON sys.Spotify_song (song_popularity);
select song_popularity from Spotify_song;
```

![5](5.png)

#  Analytics

BLANK

# Conclusion

BLANK

# Contributions 

- Hsiang-Hua Chen : 20% from the website, 80% created by myself
- Yuan Chai : 25% from the website, 75% created by myself

#  Citations

https://www.visual-paradigm.com/guide/data-modeling/what-is-entity-relationship-diagram/

https://en.wikipedia.org/wiki/Hyperparameter_(machine_learning)

https://towardsdatascience.com/what-are-hyperparameters-and-how-to-tune-the-hyperparameters-in-a-deep-neural-network-d0604917584a

https://towardsdatascience.com/hyperparameters-in-deep-learning-927f7b2084dd

https://www.w3schools.com/sql/sql_create_index.asp

https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-2017

https://www.w3schools.com/sql/sql_view.asp

#  License

MIT License

Copyright (c) 2019 Hsiang-Hua Chen, Yuan Chai

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.